import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Navbar from '../components/Navbar';
import Main from '../components/Main';
import Project from '../components/Project';
import Mint from './Mint';
import Contact from './Contact.tsx';
//Import Web3 Specific Functions 

import {useEffect, useRef, useState} from 'react';
import { NFT_ADDRESS,abi } from './constants';
import Web3 from 'web3'
import {ethers, Contract, utils, proivders, providers} from 'ethers';
import Web3Modal from 'web3modal';



export default function Home() {
//Contract Initiate States

const [tokenIdsMinted, setTokenIdsMinted] = useState(0);
const [isOwner, setIsOwner] = useState(false);
const [isConnected, setIsConnected] = useState(false);
const [accountAddress, setAccountAddress] = useState('');
const [loading, setLoading] = useState(false);
//catch provider as a ref
const web3modal = useRef();

//splitAddress Function
const splitString = (string) => {
  let result1 = string.substring(0,5);
  let result2 = string.substring(38,42);
  let finalResult = result1 + "..." + result2;
  return finalResult;
};


//getProviderOrSigner -> gets provider or signer from web3
const getProviderOrSigner = async(needSigner = false) =>  { 
  //Get access to provider 
  const provider = await web3modal.current.connect();
  const web3Provider = new providers.Web3Provider(provider);
  //Get access to the signer
  const signer = web3Provider.getSigner();
  const address = await  signer.getAddress();
  console.l
  //Split the address
  const subStringAddress = splitString(address);
  setAccountAddress(subStringAddress);
  console.log(accountAddress);

  //Make sure user is using the Rinkeby TestNet Network 

  const {chainId} = await web3Provider.getNetwork();
  if(chainId !==4) { 
    window.alert("Change Network To Rinkeby");
  }
  if(needSigner) { 
    const signer = web3Provider.getSigner();
    return signer;
  }

  return web3Provider;


};

const Connect = async() =>  {
  try { 
    await getProviderOrSigner();
    setIsConnected(true)
  }catch(err) { 
    console.error(err)
  }

}





useEffect(() => { 
  if(!isConnected) { 
    web3modal.current = new Web3Modal({
      network: "rinkeby",
      providerOptions: {},
      disableInjectedProvider: false,

    })
  }
})


  return (
    <div className={styles.container}>
      <Head>
        <title>Sydney Sanders Portolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" />
      </Head>

          <div className = "body_Wrapper">
              <Navbar
                Connect={Connect}
                accountAddress = {accountAddress}
                isConnected = {isConnected}
              />


              <section className = "home">

              <div className = "home_Header">
    
                    <div className = "heading_Contents">
                      <p>Hi! There !</p>
                        <span id ="line"></span>
                      <h1>I'm Sydney Sanders</h1>
                        <h2> Front-End Developer </h2>
                        <h3>I Like To Keep Things Very Minimal.</h3>
                        <button className = "explore">
                            Explore My Work
                          </button>

                      </div>
                    <div className = "imageSphere">
                        <Image src = "/Group.png" alt = "group" width={900} height = {900}></Image>
                      </div>
                    </div>

              </section>

          </div>

          
        <section className = "divide">
                <div className = "divideLine"></div>
              </section>
    
        <Main />


        <section className = "divide clear">
                <div className = "divideLine"></div>
              </section>


              <section className ="skills">
              <div className = "whatIDo">
              <h2>Skills </h2>
            </div>
              <Image className = "skills_Image" alt ="Skills" src = "/Skills.png" width={290} height ={250} />
                <div className = "skill_Card">
                    <div className = "card">
                      <div className = "card1">
                        <div className = "subCard">
                            HTML 
                          </div>
                          
                        <div className = "subCard card_Top">
                            React 
                          </div>
                          
                        <div className = "subCard card_Top">
                            Git 
                          </div>
                   
                          
                            </div>
                      <div className = "card1">
                      <div className = "subCard">
                          
                          CSS 
                        
                        </div>
                               
                        <div className = "subCard card_Top">
                            NextJs 
                          </div>
                               
                       
                        <div className = "subCard card_Top">
                            EtherJs 
                          </div>
                        <div className = "poly">
                            <Image  className='polyGon' alt = "polyGon" src = '/PolyGon.png' width={14} height ={14}></Image>
                          </div>
                            </div>
                      <div className = "card1">
                      <div className = "subCard">
                          
                          Javascript 
                        
                        </div>
                        <div className = "subCard card_Top">
                            Solidity 
                          </div>
                        <div  className  = "subCard card_Top">
                            NodeJs 
                          </div>
                               
                            </div>
                    
                          </div>
              
              </div>
                </section>

              <Project />
              <Mint />
              <Contact />




    </div>
  )
}
